#Modify lines indicated with MODIFY
__default__:
  queue: 'standard' #MODIFY
  group: 'aponsero' #MODIFY
  M: 'aponsero@email.arizona.edu' #MODIFY
  walltime: 'walltime=12:00:00'
  select: 'select=1:ncpus=12:mem=100gb'
  m: 'bea'
  o: 'out/{rule}.{wildcards}.out'
  e: 'err/{rule}.{wildcards}.err'

#rename:
#  walltime: '01:00:00'
#  mem: '1000mb'




